models/Article.php
<?php

namespace app\models;

use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\SluggableBehavior;
use yii\behaviors\TimestampBehavior;
use yii\helpers\Url;

/**
 * This is the model class for table "article".
 *
 * @property integer $id
 * @property string $title
 * @property string $slug
 * @property string $content
 * @property string $excerpt
 * @property integer $created_at
 * @property integer $created_by
 * @property integer $category
 * @property string $image
 *
 * @property User $createdBy
 */
class Article extends \yii\db\ActiveRecord {

    const CATEGORY_PAGES = 0;
    const CATEGORY_NEWS = 1;
    const CATEGORY_EXPERT = 2;
    const CATEGORY_WORKS = 3;

    public function behaviors() {
        return [
            [
                'class'        => SluggableBehavior::className(),
                'attribute'    => 'title',
                'ensureUnique' => true,
                'immutable'    => true,
                // 'slugAttribute' => 'slug',
            ],
            /*[
                'class'              => TimestampBehavior::className(),
                'createdAtAttribute' => 'created_at',
                'updatedAtAttribute' => false,
//                'value' => new Expression('NOW()'),
            ],*/
            [
                'class'              => BlameableBehavior::className(),
                'createdByAttribute' => 'created_by',
                'updatedByAttribute' => false,
            ],
            [
                'class' => \yiidreamteam\upload\ImageUploadBehavior::className(),
                'attribute' => 'image',
                'thumbs' => [
                    'thumb' => ['width' => 300, 'height' => 400],
                    'promo' => ['width' => 360, 'height' => 250],
                    'square' => ['width' => 150, 'height' => 150],
                ],
                'filePath' => '@webroot/uploads/images/articles/[[pk]].[[extension]]',
                'fileUrl' => '/uploads/images/articles/[[pk]].[[extension]]',
                'thumbPath' => '@webroot/uploads/images/articles/[[pk]]_[[profile]].[[extension]]',
                'thumbUrl' => '/uploads/images/articles/[[pk]]_[[profile]].[[extension]]',
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public static function tableName() {
        return 'article';
    }

    public function scenarios() {
        $scenarios = parent::scenarios();

        $scenarios['edit'] = [ 'title', 'content', 'excerpt', 'slug', 'created_at', 'category' ];
        return $scenarios;
    }

    /**
     * @inheritdoc
     */
    public function rules() {
        return [
            [ [ 'title', 'content' ], 'required' ],
            [ [ 'title', 'content', 'excerpt' ], 'string' ],
            [ [ 'category' ], 'integer' ],
            [ [ 'slug' ], 'string', 'max' => 150 ],
//            [ 'created_at', 'safe' ],
            [ 'created_at', 'date', 'format' => 'dd.MM.yyyy' ],
            [ 'image', 'file', 'extensions' => 'jpeg, gif, png' ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels() {
        return [
            'id'         => 'ID',
            'title'      => 'Название',
            'slug'       => 'URL',
            'content'    => 'Текст',
            'excerpt'    => 'Вступление',
            'created_at' => 'Время создания',
            'created_by' => 'Автор',
            'category'   => 'Категория',
            'image'   => 'Изображение',
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints() {
        return [
            'excerpt' => 'Отображается только на главной странице и в списке новостей',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCreatedBy() {
        return $this->hasOne( User::className(), [ 'id' => 'created_by' ] );
    }

    /**
     * @inheritdoc
     * @return ArticleQuery the active query used by this AR class.
     */
    public static function find() {
        return new ArticleQuery( get_called_class() );
    }

    public function afterValidate() {
        if ( $this->scenario == 'edit' ) {
            if ( $this->created_at ) {
                $this->created_at = strtotime( $this->created_at );
            } else {
                $this->created_at = time();
            }
        }
        parent::afterValidate();
    }

    public static function getCategories() {
        return [
            self::CATEGORY_PAGES => 'Страницы',
            self::CATEGORY_NEWS  => 'Новости',
            self::CATEGORY_EXPERT  => 'Эксперты',
            self::CATEGORY_WORKS  => 'Работы',
        ];
    }

    public static function getCategoryCodes() {
        return [
            self::CATEGORY_PAGES => 'page',
            self::CATEGORY_NEWS  => 'news',
            self::CATEGORY_EXPERT  => 'expert',
            self::CATEGORY_WORKS  => 'works',
        ];
    }

    public function getCategoryName( $id = null ) {
        if ( ! $id ) {
            $id = $this->category;
        }
        if ( ! isset( $this->categories[ $id ] ) ) {
            $id = self::CATEGORY_PAGES;
        }

        return $this->categories[ $id ];
    }

    public function getCategoryCode( $id ) {
        if ( ! isset( $this->categoryCodes[ $id ] ) ) {
            $id = self::CATEGORY_PAGES;
        }

        return $this->categoryCodes[ $id ];
    }

    public function getRoute() {
        $result = [ 'article/view', 'slug' => $this->slug ];

        if ( $this->category !== self::CATEGORY_PAGES ) {
            $result['category'] = $this->getCategoryCode( $this->category );
        }

        return $result;
    }

    public function getUrl() {
        return Url::to( $this->getRoute() );
    }

    public function getLead() {
        return nl2br( trim( strip_tags( $this->excerpt ) ) );
    }
}

controllers/ArticleController.php
<?php

namespace app\controllers;

use vova07\imperavi\actions\GetAction;
use Yii;
use app\models\Article;
use app\models\search\Article as ArticleSearch;
use yii\helpers\Url;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * ArticleController implements the CRUD actions for Article model.
 */
class ArticleController extends Controller {

    private $_filesPaths = [ ];

    public function init() {
        $this->_filesPaths = [
            'imageUrl'  => Url::to( '@web/uploads/images/', true ),
            'imagePath' => '@webroot/uploads/images',
            'fileUrl'   => Url::to( '@web/uploads/files/', true ),
            'filePath'  => '@webroot/uploads/files',
        ];
        parent::init();
    }

    public function behaviors() {
        return [
            'verbs' => [
                'class'   => VerbFilter::className(),
                'actions' => [
                    'delete' => [ 'post' ],
                ],
            ],
        ];
    }

    public function actions() {
        return [
            'images-get'   => [
                'class' => 'vova07\imperavi\actions\GetAction',
                'url'   => $this->_filesPaths['imageUrl'], // Directory URL address, where files are stored.
                'path'  => $this->_filesPaths['imagePath'], // Or absolute path to directory where files are stored.
                'type'  => GetAction::TYPE_IMAGES,
            ],
            'image-upload' => [
                'class' => 'vova07\imperavi\actions\UploadAction',
                'url'   => $this->_filesPaths['imageUrl'],
                // URL адрес папки куда будут загружатся изображения.
                'path'  => $this->_filesPaths['imagePath']
                // Или абсолютный путь к папке куда будут загружатся изображения.
            ],
            'files-get'    => [
                'class' => 'vova07\imperavi\actions\GetAction',
                'url'   => $this->_filesPaths['fileUrl'], // Directory URL address, where files are stored.
                'path'  => $this->_filesPaths['filePath'], // Or absolute path to directory where files are stored.
                'type'  => GetAction::TYPE_FILES,
            ],
            'file-upload'  => [
                'class' => 'vova07\imperavi\actions\UploadAction',
                'url'   => $this->_filesPaths['fileUrl'],
                // URL адрес папки куда будут загружатся изображения.
                'path'  => $this->_filesPaths['filePath']
                // Или абсолютный путь к папке куда будут загружатся изображения.
            ],
        ];
    }

    /**
     * Lists all Article models.
     *
     * @return mixed
     * @throws NotFoundHttpException
     */
    public function actionIndex() {
        if ( ! \Yii::$app->user->can( 'addNews' ) ) {
            throw new NotFoundHttpException( 'Страница не найдена' );
        }
        $searchModel  = new ArticleSearch();
        $dataProvider = $searchModel->search( Yii::$app->request->queryParams );

        return $this->render( 'index', [
            'searchModel'  => $searchModel,
            'dataProvider' => $dataProvider,
        ] );
    }

    /**
     * Displays a single Article model.
     *
     * @param $slug
     * @param string $category
     *
     * @return mixed
     * @throws NotFoundHttpException
     * @internal param int $id
     *
     */
    public function actionView( $slug, $category = 'page' ) {
        return $this->render( 'view', [
            'model' => $this->findModelbySlug( $slug, $category ),
        ] );
    }

    /**
     * Creates a new Article model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     *
     * @return mixed
     * @throws NotFoundHttpException
     */
    public function actionCreate() {
        if ( ! \Yii::$app->user->can( 'addNews' ) ) {
            throw new NotFoundHttpException( 'Страница не найдена' );
        }
        $model = new Article();
        $model->scenario = 'edit';

        if ( $model->load( Yii::$app->request->post() ) && $model->save() ) {
            return $this->redirect( $model->route );
        } else {
            return $this->render( 'create', [
                'model' => $model,
            ] );
        }
    }

    /**
     * Updates an existing Article model.
     * If update is successful, the browser will be redirected to the 'view' page.
     *
     * @param integer $id
     *
     * @return mixed
     * @throws NotFoundHttpException
     */
    public function actionUpdate( $id ) {
        if ( ! \Yii::$app->user->can( 'addNews' ) ) {
            throw new NotFoundHttpException( 'Страница не найдена' );
        }

        $model = $this->findModel( $id );
        $model->scenario = 'edit';

        if ( $model->load( Yii::$app->request->post() ) && $model->save() ) {
            return $this->redirect( $model->route );
        } else {
            return $this->render( 'update', [
                'model' => $model,
            ] );
        }
    }

    /**
     * Deletes an existing Article model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     *
     * @param integer $id
     *
     * @return mixed
     * @throws NotFoundHttpException
     * @throws \Exception
     */
    public function actionDelete( $id ) {
        if ( ! \Yii::$app->user->can( 'addNews' ) ) {
            throw new NotFoundHttpException( 'Страница не найдена' );
        }
        $this->findModel( $id )->delete();

        return $this->redirect( [ 'index' ] );
    }

    /**
     * Finds the Article model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     *
     * @param $slug
     * @param null|string $category Category name (i.e 'news', 'photo' etc.)
     *
     * @return Article the loaded model
     * @throws NotFoundHttpException
     * @internal param int $id
     *
     */
    protected function findModelbySlug( $slug, $category = null ) {
        $model = Article::find()->bySlug( $slug );
        if ( $category ) {
            $model = $model->andCategory( $category );
        }
        $model = $model->one();
        if ( ( $model ) !== null ) {
            return $model;
        } else {
            throw new NotFoundHttpException( 'Страница не найдена' );
        }
    }

    /**
     * Finds the Article model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     *
     * @param $id
     *
     * @return Article the loaded model
     * @throws NotFoundHttpException
     * @internal param $slug
     * @internal param null|string $category Category name (i.e 'news', 'photo' etc.)
     *
     * @internal param int $id
     */
    protected function findModel( $id ) {
        $model = Article::findOne( $id );
        if ( ( $model ) !== null ) {
            return $model;
        } else {
            throw new NotFoundHttpException( 'Страница не найдена' );
        }
    }
}

views/article/_form.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;
use vova07\imperavi\Widget;

/* @var $this yii\web\View */
/* @var $model app\models\Article */
/* @var $form yii\widgets\ActiveForm */
?>
<div class="article-form">

    <?php $form = ActiveForm::begin( [
        'options' => [
            'enctype' => 'multipart/form-data',
        ],
    ] ); ?>
    <?= $form->errorSummary( $model ); ?>
    <?= $form->field( $model, 'category' )->dropDownList(
        $model->categories
    ) ?>

    <?= $form->field( $model, 'title' )->textInput() ?>

    <?= $form->field( $model, 'slug' )->textInput( [ 'maxlength' => true ] ) ?>

    <?= $form->field( $model, 'image' )->fileInput( [ 'accept' => 'image/*' ] ) ?>
    <?php if ( $model->image ) { ?>
        <div class="image-preview">
            <?= Html::img( $model->getThumbFileUrl( 'image', 'thumb' ),
                [ 'class' => 'img-thumbnail' ] ); ?>
            <?= Html::img( $model->getThumbFileUrl( 'image', 'square' ),
                [ 'class' => 'img-thumbnail' ] ); ?>
            <div class="alert alert-info">
                Если вы загрузите новое изображение, это будет удалено.
            </div>
        </div>
    <?php } ?>

    <?= $form->field( $model, 'excerpt' )->textarea( [ 'rows' => 3 ] ) ?>

    <?= $form->field( $model, 'content' )->widget( Widget::className(), [
        'settings' => [
            'lang'             => 'ru',
            'minHeight'        => 200,
            'imageManagerJson' => Url::to( [ '/article/images-get' ] ),
            'fileManagerJson'  => Url::to( [ '/article/files-get' ] ),
            'imageUpload'      => Url::to( [ '/article/image-upload' ] ),
            'fileUpload'       => Url::to( [ '/article/file-upload' ] ),
            'plugins'          => [
//                'clips',
//                'fullscreen',
                'imagemanager',
                'filemanager',
                'table',
                'counter',
                'video',
            ]
        ]
    ] ); ?>

    <?= $form->field( $model, 'created_at' )->widget( \yii\jui\DatePicker::classname(), [
        'language'   => 'ru',
        'inline'     => false,
        'dateFormat' => 'dd.MM.yyyy',
    ] ) ?>

    <div class="form-group">
        <?= Html::submitButton( $model->isNewRecord ? 'Добавить' : 'Обновить',
            [ 'class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary' ] ) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/article/_item-detail.php
<?php
/**
 * _item.php
 * Created by h8every1 on 07.07.2015 1:52
 */

/* @var $this yii\web\View */
/* @var $model app\models\Article */
/* @var $key mixed the key value associated with the data item */
/* @var $index integer the zero-based index of the data item in the items array returned by [[dataProvider]] */
/* @var $widget yii\widgets\ListView, this widget instance */


use yii\helpers\Html;
use yii\helpers\Url;

?>
<div class="b-post">
    <h2 class="b-post--title">
        <?php echo Html::a( Html::encode( $model->title ), $model->route ); ?>
    </h2>

    <div class="b-post--meta">
        <?php if ( \Yii::$app->user->can( 'addNews' ) ) { ?>
            <div class="b-post--metaitem b-post--metaitem__edit">
                <?= Html::a( 'Изменить', [ 'article/update', 'id' => $model->id ], [ 'class' => 'btn btn-primary' ] ) ?>
            </div>
        <?php } ?>
    </div>

    <div class="b-post--content">
        <?php echo $model->content; ?>
    </div>
    <div class="b-share-buttons">
        <div class="social-likes social-likes_notext" data-url="<?= Url::to($model->route, true); ?>" data-title="<?= $model->title; ?>">
            <div class="vkontakte" title="Поделиться ссылкой во Вконтакте"></div>
            <div class="odnoklassniki" title="Поделиться ссылкой в Одноклассниках"></div>
            <div class="twitter" title="Поделиться ссылкой в Твиттере"></div>
            <div class="facebook" title="Поделиться ссылкой на Фейсбуке"></div>
        </div>
    </div>
</div>

views/article/_item.php
<?php
/**
 * _item.php
 * Created by h8every1 on 07.07.2015 1:52
 */

/* @var $this yii\web\View */
/* @var $model app\models\Article */
/* @var $key mixed the key value associated with the data item */
/* @var $index integer the zero-based index of the data item in the items array returned by [[dataProvider]] */
/* @var $widget yii\widgets\ListView, this widget instance */


use yii\helpers\Html;
use yii\helpers\Url;

?>
<div class="b-post">
    <h2 class="b-post--title">
        <?php echo Html::a( Html::encode( $model->title ), $model->route ); ?>
    </h2>

    <div class="b-post--meta">
        <div class="b-post--metaitem b-post--metaitem__date">
            <?= \Yii::$app->formatter->asDate( $model->created_at, 'medium' ); ?>
        </div>
        <?php if ( \Yii::$app->user->can( 'addNews' ) ) { ?>
            <div class="b-post--metaitem b-post--metaitem__edit">
                <?= Html::a( 'Изменить', [ 'article/update', 'id' => $model->id ], [ 'class' => 'btn btn-primary' ] ) ?>
            </div>
        <?php } ?>
    </div>

    <div class="b-post--content">
        <?php echo $model->lead; ?>
    </div>
    <div class="b-share-buttons">
        <div class="social-likes social-likes_notext" data-url="<?= Url::to($model->route, true); ?>" data-title="<?= $model->title; ?>">
            <div class="vkontakte" title="Поделиться ссылкой во Вконтакте"></div>
            <div class="odnoklassniki" title="Поделиться ссылкой в Одноклассниках"></div>
            <div class="twitter" title="Поделиться ссылкой в Твиттере"></div>
            <div class="facebook" title="Поделиться ссылкой на Фейсбуке"></div>
        </div>
    </div>
</div>

views/article/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\search\Article */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="article-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'title') ?>

    <?= $form->field($model, 'slug') ?>

    <?= $form->field($model, 'content') ?>

    <?= $form->field($model, 'created_at') ?>

    <?php // echo $form->field($model, 'created_by') ?>

    <?php // echo $form->field($model, 'category') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/article/create.php
<?php

use app\helpers\ViewHelper;
use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Article */

$this->title                   = 'Добавление текстового материала';
$this->params['breadcrumbs'][] = [ 'label' => 'Материалы', 'url' => [ 'index' ] ];
$this->params['breadcrumbs'][] = [ 'label' => 'Добавление'  ];
$this->params['show_breadcrumbs'] = true;
?>
<?= ViewHelper::breadcrumbs(); ?>
<div class="container">
    <div class="article-create">

        <?= $this->render( '_form', [
            'model' => $model,
        ] ) ?>

    </div>
</div>

views/article/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\ListView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\search\Article */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title                   = $searchModel->categoryName;
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="container">
    <div class="article-index">

        <h1><?= Html::encode( $this->title ) ?></h1>
        <?php // echo $this->render('_search', ['model' => $searchModel]); ?>


        <p>
            <?= Html::a( 'Добавить материал', [ 'create' ], [ 'class' => 'btn btn-success' ] ) ?>
        </p>

        <?= GridView::widget( [
            'dataProvider' => $dataProvider,
            'filterModel'  => $searchModel,
            'columns'      => [
//                [ 'class' => 'yii\grid\SerialColumn' ],
//                'id',
                'title:ntext',
//                'slug',
//                'content:html',
                'created_at:date',
                // 'created_by',
                [
                    'attribute' => 'category',
                    'value'     => function ( $model ) {
                        return $model->categoryName;
                    },
                    'filter'    => \app\models\search\Article::getCategories()

                ],
                [
                    'class'   => yii\grid\ActionColumn::className(),
                    'buttons' => [
                        'view' => function ( $url, $model, $key ) {
                            return Html::a( '<span class="glyphicon glyphicon-eye-open"></span>', $model->route );
                        }
                    ],

                ],
            ],
        ] ); ?>

    </div>
</div>

views/article/list-detail.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\ListView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\search\Article */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title                   = $searchModel->categoryName;
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="container">
    <div class="article-index">

        <h1><?= Html::encode( $this->title ) ?></h1>
        <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

        <?= ListView::widget( [
            'dataProvider' => $dataProvider,
            'itemOptions' => ['class' => 'item'],
            'itemView' => '_item-detail',
            'summary' => '',
        ] ); ?>

    </div>
</div>

views/article/list.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\ListView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\search\Article */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title                   = $searchModel->categoryName;
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="container">
    <div class="article-index">

        <h1><?= Html::encode( $this->title ) ?></h1>
        <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

        <?= ListView::widget( [
            'dataProvider' => $dataProvider,
            'itemOptions' => ['class' => 'item'],
            'itemView' => '_item',
            'summary' => '',
        ] ); ?>

    </div>
</div>

views/article/update.php
<?php

use app\helpers\ViewHelper;
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Article */

$this->title                   = $model->title;
$this->params['breadcrumbs'][] = [ 'label' => 'Материалы', 'url' => [ 'index' ] ];
$this->params['breadcrumbs'][] = [ 'label' => $model->title, 'url' => [ 'view', 'id' => $model->id ] ];
$this->params['breadcrumbs'][] = 'Редактирование';
?>
<?= ViewHelper::breadcrumbs(); ?>
<div class="container">
    <div class="article-update">

        <h1><?= Html::encode( $this->title ) ?></h1>

        <?= $this->render( '_form', [
            'model' => $model,
        ] ) ?>

    </div>
</div>

views/article/view.php
<?php

use app\helpers\ViewHelper;
use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Article */

$this->title = $model->title;
?>
<?= ViewHelper::breadcrumbs(); ?>

<div class="container">
    <div class="b-post">
        <?php if ( \Yii::$app->user->can( 'addNews' ) ) { ?>
            <p>
                <?= Html::a( 'Изменить', [ 'update', 'id' => $model->id ], [ 'class' => 'btn btn-primary' ] ) ?>
                <?= Html::a( 'Удалить', [ 'delete', 'id' => $model->id ], [
                    'class' => 'btn btn-danger',
                    'data'  => [
                        'confirm' => 'Вы уверены, что хотите удалить этот материал?',
                        'method'  => 'post',
                    ],
                ] ) ?>
            </p>
        <?php } ?>
        <div class="b-post--content">
            <?= $model->content; ?>
        </div>
        <div class="b-share-buttons">
            <div class="social-likes">
                <div class="vkontakte" title="Поделиться ссылкой во Вконтакте">ВКонтакте</div>
                <div class="odnoklassniki" title="Поделиться ссылкой в Одноклассниках">Одноклассники</div>
                <div class="twitter" data-via="sibdepo" title="Поделиться ссылкой в Твиттере">Twitter</div>
                <div class="facebook" title="Поделиться ссылкой на Фейсбуке">Facebook</div>
            </div>
        </div>
    </div>
</div>