controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\PasswordResetRequestForm;
use app\models\ResetPasswordForm;
use app\models\Work;
use Yii;
use yii\base\InvalidParamException;
use yii\filters\AccessControl;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use app\models\SignupForm;
use app\models\Article;
use app\models\search\Article as ArticleSearch;
use yii\web\NotFoundHttpException;

class SiteController extends Controller {
    public function behaviors() {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only'  => [ 'logout' ],
                'rules' => [
                    [
                        'actions' => [ 'logout' ],
                        'allow'   => true,
                        'roles'   => [ '@' ],
                    ],
                ],
            ],
            'verbs'  => [
                'class'   => VerbFilter::className(),
                'actions' => [
                    'logout' => [ 'post' ],
                ],
            ],
        ];
    }

    public function actions() {
        return [
            'error'   => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class'           => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function actionIndex() {

        $works       = Work::find()->count();
        $polozhenie  = Article::find()->bySlug( 'polozhenie' )->one();
        $main  = Article::find()->bySlug( 'main' )->one();
        $nominations = Article::find()->bySlug( 'nominations' )->one();
        $news = Article::find()->andCategory( 'news' )->orderBy( 'created_at DESC' )->limit( 3 )->all();
        $works_articles = Article::find()->andCategory( 'works' )->orderBy( 'created_at DESC' )->limit( 12 )->all();
//        $expert = Article::find()->andCategory( 'expert' )->orderBy( 'created_at DESC' )->limit( 4 )->all();
//        $howto = Article::find()->bySlug( 'howto' )->limit( 1 )->one();

        return $this->render( 'index',
            [
                'worksCount'  => $works,
                'polozhenie'  => $polozhenie,
                'main'  => $main,
//                'howto'       => $howto,
                'nominations' => $nominations,
                'news'        => $news,
                'works'        => $works_articles,
//                'expert'      => $expert,
            ] );
    }

    public function actionLogin() {
        if ( ! \Yii::$app->user->isGuest ) {
            return $this->redirect( [ 'user/profile' ] );
        }

        $model = new LoginForm();

        if ( $model->load( Yii::$app->request->post() ) && $model->login() ) {
            return $this->redirect( [ 'user/profile' ] );
        } else {
            return $this->render( 'login', [
                'model' => $model,
            ] );
        }
    }

    public function actionLogout() {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    public function actionContact() {
        $model = new ContactForm();
        if ( $model->load( Yii::$app->request->post() ) && $model->contact( Yii::$app->params['adminEmail'] ) ) {
            Yii::$app->session->setFlash( 'contactFormSubmitted' );

            return $this->refresh();
        } else {
            return $this->render( 'contact', [
                'model' => $model,
            ] );
        }
    }

    public function actionAbout() {
        return $this->render( 'about' );
    }

    public function actionVerify() {
        if ( \Yii::$app->user->isGuest ) {
            throw new NotFoundHttpException( 'Страница не найдена.' );
        } elseif ( \Yii::$app->user->identity->isActivated() ) {
            return $this->redirect( [ 'user/profile' ] );
        }

        $model = new SignupForm( [ 'scenario' => 'activate' ] );
        if ( $model->load( Yii::$app->request->get() ) ) {
            if ( $user = $model->activate() ) {
                if ( Yii::$app->getUser()->login( $user ) ) {
                    Yii::$app->session->setFlash( 'success', 'Аккаунт подтвержден!' );

                    return $this->goHome();
                }
            }
        }

        return $this->render( 'verify', [
            'model' => $model,
        ] );
    }

    public function actionResendCode() {
        echo 'Resending the code...';
        if ( ! Yii::$app->user->isGuest && ! Yii::$app->user->identity->isActivated() ) {
            Yii::$app->session->setFlash( 'activationCodeResent' );
            Yii::$app->user->identity->sendConfirmEmail();

            return $this->redirect( [ 'verify' ] );
        } else {
            return $this->redirect( [ 'site/index' ] );
        }
    }

    public function actionNews() {
        $searchModel                                         = new ArticleSearch();
        $searchArray                                         = Yii::$app->request->queryParams;
        $searchArray[ $searchModel->formName() ]['category'] = Article::CATEGORY_NEWS;
        $dataProvider                                        = $searchModel->search( $searchArray );

        return $this->render( '/article/list', [
            'searchModel'  => $searchModel,
            'dataProvider' => $dataProvider,
        ] );
    }

    public function actionExperts() {
        $searchModel                                         = new ArticleSearch();
        $searchArray                                         = Yii::$app->request->queryParams;
        $searchArray[ $searchModel->formName() ]['category'] = Article::CATEGORY_EXPERT;
        $dataProvider                                        = $searchModel->search( $searchArray );

        return $this->render( '/article/list-detail', [
            'searchModel'  => $searchModel,
            'dataProvider' => $dataProvider,
        ] );
    }

    public function actionNominationsList() {
        $nominations = Work::allNominations();
        $descriptions = Work::getNominationsDescriptions();
        $data        = [ ];

        foreach ( $nominations as $id => $name ) {
            $data[] = [
                'id'    => $id,
                'name'  => $name,
                'description'  => $descriptions[$id],
                'count' => (int) Work::find()->in_nomination( $id )->count()
            ];
        }

        return $this->render( 'nominations-list', [
            'data'  => $data,
            'total' => (int) Work::find()->count()
        ] );
    }

	public function actionWorks() {

		$works_articles = Article::find()->andCategory( 'works' )->orderBy( 'created_at DESC' )->all();

		return $this->render( 'works',
			[
				'works'        => $works_articles,
			] );
	}

    /**
     * Requests password reset.
     *
     * @return mixed
     */
    public function actionRequestPasswordReset() {
        $model = new PasswordResetRequestForm();
        if ( $model->load( Yii::$app->request->post() ) && $model->validate() ) {
            if ( $model->sendEmail() ) {
                Yii::$app->session->setFlash( 'success', 'Проверьте свой e-mail для дальнейших шагов по восстановлению пароля.' );

                return $this->goHome();
            } else {
                Yii::$app->session->setFlash( 'error', 'К сожалению, лдя этого e-mail адреса невозможно восстановить пароль.' );
            }
        }

        return $this->render( 'requestPasswordResetToken', [
            'model' => $model,
        ] );
    }

    /**
     * Resets password.
     *
     * @param string $token
     *
     * @return mixed
     * @throws BadRequestHttpException
     */
    public function actionResetPassword( $token ) {
        try {
            $model = new ResetPasswordForm( $token );
        } catch ( InvalidParamException $e ) {
            throw new BadRequestHttpException( $e->getMessage() );
        }
        if ( $model->load( Yii::$app->request->post() ) && $model->validate() && $model->resetPassword() ) {
            Yii::$app->session->setFlash( 'success', 'Новый пароль сохранен.' );

            return $this->goHome();
        }

        return $this->render( 'resetPassword', [
            'model' => $model,
        ] );
    }

}

views/site/about.php
<?php
use yii\helpers\Html;

/* @var $this yii\web\View */
$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        This is the About page. You may modify the following file to customize its content:
    </p>

    <code><?= __FILE__ ?></code>
</div>

views/site/contact.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

    <div class="alert alert-success">
        Thank you for contacting us. We will respond to you as soon as possible.
    </div>

    <p>
        Note that if you turn on the Yii debugger, you should be able
        to view the mail message on the mail panel of the debugger.
        <?php if (Yii::$app->mailer->useFileTransport): ?>
        Because the application is in development mode, the email is not sent but saved as
        a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
        Please configure the <code>useFileTransport</code> property of the <code>mail</code>
        application component to be false to enable email sending.
        <?php endif; ?>
    </p>

    <?php else: ?>

    <p>
        If you have business inquiries or other questions, please fill out the following form to contact us. Thank you.
    </p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>
                <?= $form->field($model, 'name') ?>
                <?= $form->field($model, 'email') ?>
                <?= $form->field($model, 'subject') ?>
                <?= $form->field($model, 'body')->textArea(['rows' => 6]) ?>
                <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                    'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                ]) ?>
                <div class="form-group">
                    <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                </div>
            <?php ActiveForm::end(); ?>
        </div>
    </div>

    <?php endif; ?>
</div>

views/site/error.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

$this->title = 'Ошибка!';
?>
<div class="container marg75">
    <div class="row">
        <div class="col-lg-12">
            <div class="main_pad">
                <strong class="colored oops">Ой, ошибка 404!</strong><br><br>
                <p><?= nl2br( Html::encode( $message ) ) ?></p>
            </div>
        </div>
    </div>
</div>

views/site/index.php
<?php
/* @var $this yii\web\View */
use app\assets\LightboxAsset;
use app\widgets\Alert;
use yii\helpers\Html;
use yii\helpers\Url;

/* @var $worksCount int */
/* @var $polozhenie \app\models\Article */
/* @var $howto \app\models\Article */
/* @var $main \app\models\Article */
/* @var $nominations \app\models\Article */
/* @var $news \app\models\Article */
/* @var $works \app\models\Article */
/* @var $expert \app\models\Article */

LightboxAsset::register( $this );
$this->title                      = \Yii::$app->name;
$this->params['hide_breadcrumbs'] = true;
?>
<div class="container">
	<div class="site-index">
		<?= Alert::widget( [ 'closeButton' => false ] ) ?>

		<div class="jumbotron b-intro"></div>
		<div class="body-content">
			<h2>О конкурсе</h2>

			<div class="b-news-item__main">
				<div class="b-news-item--excerpt">
					<?= $main->content; ?>
				</div>
			</div>
			<div class="row">
				<div class="col-md-6">

					<h2>Как подать заявку</h2>

					<div class="b-news-item__main">
						<div class="b-news-item--excerpt">
							<iframe src="//www.slideshare.net/slideshow/embed_code/key/7C0iO7LO8RfA1P" width="595"
							        height="485" frameborder="0" marginwidth="0" marginheight="0" scrolling="no"
							        style="border:1px solid #CCC; border-width:1px; margin-bottom:5px; max-width: 100%;"
							        allowfullscreen></iframe>
							<div style="margin-bottom:5px"><strong> <a
										href="//www.slideshare.net/Editor-Education/pro-63240064"
										title="Как подать заявку на конкурс &quot;Фото PRO Образование&quot;"
										target="_blank">Как подать заявку на конкурс &quot;Фото PRO
										Образование&quot;</a> </strong>
							</div>
						</div>

					</div>
				</div>
				<div class="col-md-6">
					<h2><?= Html::a( 'Последние новости', Url::to( [ 'site/news' ] ) ) ?></h2>
					<?php
					foreach ( $news as $news_item ) {
						?>
						<div class="b-news-item__main">
							<small class="b-news-item--date"><?= date( 'd.m.Y', $news_item->created_at ); ?></small>
							<h4 class="b-news-item--title"><?= Html::a( $news_item->title,
									Url::to( $news_item->url ) ); ?></h4>
							<?php
							$lead = $news_item->lead;
							if ( $lead ) { ?>
								<div class="b-news-item--excerpt">
									<?= $lead; ?>
								</div>
							<?php } ?>
						</div>
						<?php
					}

					?>
				</div>
			</div>
		</div>
	</div>
</div>
<?php if ( $worksCount > 0 ) { ?>
	<div class="prl-1">
		<div class="prlx">
			<div class="container">
				<div class="stats-primary">
					<div class="stats-block stats-top">
						<div class="aio-icon-top">
							<div class="aio-icon none"><i class="icon-happy"></i></div>
						</div>
						<div class="stats-desc">
							<div class="stats-text">На конкурс <?= \Yii::t( 'app',
									'{n, plural, one{подана} few{подано} other{подано}}',
									[ 'n' => $worksCount ]
								); ?></div>
							<div class="stats-number number-counter" data-number="<?= $worksCount; ?>"><span
									class="number-count"><?= $worksCount; ?></span>
							</div>
							<div class="stats-text"><?= \Yii::t( 'app',
									'{n, plural, one{работа} few{работы} many{работ} other{работы}}',
									[ 'n' => $worksCount ]
								); ?></div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
<?php } ?>
<div class="container">
	<div class="row">
		<div class="col-lg-12">
			<div class="promo-block">
				<div class="promo-text">
					<?= Html::a('Примеры поданых работ', Url::to(['site/works'], true));?></div>
			</div>
		</div>
	</div>


	<div class="marg30">
		<?php foreach ( $works as $works_item ) {
			?><div class="photo-preview">
				<div class="blog-main">
					<div class="blog-images">
						<div class="post-thumbnail">

							<?= Html::a( Html::img( $works_item->getThumbFileUrl( 'image', 'promo' ),
								[ 'class' => 'work-photo' ] ), Url::to( $works_item->getImageFileUrl( 'image' ) ), ['class'=>'image-link','title'=>$works_item->title] ) ?>
						</div>
					</div>
					<div class="blog-name"><?= $works_item->title; ?></div>
				</div>
			</div><?php } ?>
	</div>

</div>

views/site/login.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use app\models\Participant;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\Participant */

$this->title                   = 'Вход на сайт';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="container">
    <div class="row">

        <div class="col-sm-5">
            <div class="site-login">
                <h2>Вход</h2>

                <?php $form = ActiveForm::begin( [
                    'id'          => 'login-form',
                    'options'     => [ 'class' => 'form-horizontal' ],
                    'fieldConfig' => [
                        'template'     => "{label}\n<div class=\"col-lg-9\">{input}</div>\n<div class=\"col-lg-9 col-lg-push-3\">{error}</div>",
                        'labelOptions' => [ 'class' => 'col-lg-3 control-label' ],
                    ],
                ] ); ?>

                <?= $form->field( $model, 'email' ) ?>

                <?= $form->field( $model, 'password' )->passwordInput() ?>
                <div class="row">
                    <div class="col-lg-offset-3 col-lg-5">
                        <?= $form->field( $model, 'rememberMe' )->checkbox( [
                            'template' => "{input} {label}",
                        ] ) ?>
                    </div>
                    <div class="col-lg-4">
                        <small><?= Html::a( 'Забыли пароль?', [ 'site/request-password-reset' ] ) ?></small>
                    </div>
                </div>

                <div class="form-group">
                    <?= Html::submitButton( 'Войти', [ 'class' => 'btn btn-primary', 'name' => 'login-button' ] ) ?>
                </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>
        <div class="col-sm-offset-2 col-sm-5">
            <div class="site-signup">
                <h2>Регистрацияя</h2>
                <?= Html::a( 'Зарегистрироваться',
                    [ 'participant/register'],
                    [ 'class' => 'btn btn-block btn-primary btn-lg' ] ) ?>
            </div>
        </div>
    </div>
</div>

views/site/nominations-list.php
<?php

use app\helpers\ViewHelper;
use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $data mixed */
/* @var $total int */

$this->title = 'Номинации конкурса';
?>
<?= ViewHelper::breadcrumbs(); ?>
<div class="container">
    <div class="b-post">
        <div class="b-post--content">
                <ol>
                    <?php

                    foreach ( $data as $item ) {
                        ?>
                        <li><?= $item['name'];?> — <strong><?= $item['count']; ?> <?= \Yii::t( 'app',
                                '{n, plural, one{работа} few{работы} many{работ} other{работы}}',
                                [ 'n' => $item['count'] ]
                            ); ?></strong>
                        <p>
                            <?= $item['description'];?>
                        </p></li>
                        <?php
                    } ?>
                </ol>

            <p>Всего — <?= $total;?> <?= \Yii::t( 'app',
                    '{n, plural, one{работа} few{работы} many{работ} other{работы}}',
                    [ 'n' => $total ]
                ); ?>.</p>
        </div>
    </div>
</div>

views/site/requestPasswordResetToken.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \app\models\PasswordResetRequestForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title                   = 'Запросить сброс пароля';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="container marg75">
    <div class="row">
        <div class="col-lg-12">
            <div class="site-request-password-reset">
                <h1><?= Html::encode( $this->title ) ?></h1>

                <p>Пожалуйста, введите e-mail адрес, который вы указывали при регистрации.</p>

                <div class="row">
                    <div class="col-lg-5">
                        <?php $form = ActiveForm::begin( [ 'id' => 'request-password-reset-form' ] ); ?>

                        <?= $form->field( $model, 'email' )->label(false) ?>

                        <div class="form-group">
                            <?= Html::submitButton( 'Отправить', [ 'class' => 'btn btn-primary' ] ) ?>
                        </div>

                        <?php ActiveForm::end(); ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

views/site/resetPassword.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \app\models\ResetPasswordForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title                   = 'Сброс пароля';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="container marg75">
    <div class="row">
        <div class="col-lg-12">
            <div class="site-reset-password">
                <h1><?= Html::encode( $this->title ) ?></h1>

                <p>Пожалуйста, введите новый пароль:</p>

                <div class="row">
                    <div class="col-lg-5">
                        <?php $form = ActiveForm::begin( [ 'id' => 'reset-password-form' ] ); ?>

                        <?= $form->field( $model, 'password' )->passwordInput()->label('Пароль') ?>

                        <div class="form-group">
                            <?= Html::submitButton( 'Сохранить', [ 'class' => 'btn btn-primary' ] ) ?>
                        </div>

                        <?php ActiveForm::end(); ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

views/site/verify.php
<?php
use app\helpers\ViewHelper;
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use app\models\User;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \app\models\SignupForm */

$this->title                   = 'Подтверждение регистрации';
$this->params['breadcrumbs'][] = $this->title;
$code_resent                   = Yii::$app->session->hasFlash( 'activationCodeResent' );
?>
<?= ViewHelper::breadcrumbs(); ?>
<div class="container">
    <div class="site-мукшан">
        <?php if ( $code_resent ) { ?>

            <div class="alert alert-info">
                Код выслан на ваш e-mail. Если он не придет в течение двух минут, проверьте папку "Спам".
            </div>

        <?php } ?>

        <p>Благодарим за регистрацию на участие в конкурсе! На указанный электронный адрес отправлено письмо с кодом активации Вашей учетной записи.</p>

        <?php $form = ActiveForm::begin( [
            'id'     => 'form-signup',
            'method' => 'get',
            'action' => [ 'site/verify' ]
        ] ); ?>
        <?= $form->field( $model, 'activation_key' ); ?>
        <div class="form-group">
            <?= Html::submitButton( 'Подтвердить',
                [ 'class' => 'btn btn-primary', 'name' => 'signup-button' ] ) ?>
            <?php if ( ! $code_resent ) { ?>
                <?= Html::a( 'Выслать письмо с кодом подтверждения', [ 'site/resend-code' ],
                    [ 'class' => 'btn btn-success', 'name' => 'resend-button', ] ) ?>
            <?php } ?>
        </div>
        <?php ActiveForm::end(); ?>
    </div>
</div>

views/site/works.php
<?php
/**
 * works.php
 * Created by h8every1 on 17.07.2016 23:59
 */

/* @var $this yii\web\View */
use app\assets\LightboxAsset;
use app\helpers\ViewHelper;
use yii\helpers\Html;
use yii\helpers\Url;

LightboxAsset::register( $this );
/* @var $works \app\models\Article */
$this->title = 'Присланные работы';
?>
<?= ViewHelper::breadcrumbs(); ?>
<div class="container">
	<div class="marg30">
		<?php foreach ( $works as $works_item ) {
			?><div class="photo-preview">
			<div class="blog-main">
				<div class="blog-images">
					<div class="post-thumbnail">

						<?= Html::a( Html::img( $works_item->getThumbFileUrl( 'image', 'promo' ),
							[ 'class' => 'work-photo' ] ), Url::to( $works_item->getImageFileUrl( 'image' ) ), ['class'=>'image-link','title'=>$works_item->title] ) ?>
					</div>
				</div>
				<div class="blog-name"><?= $works_item->title; ?></div>
			</div>
			</div><?php } ?>
	</div>
</div>