controllers/FileController.php
<?php
/**
 * FileController.php
 * Created by h8every1 on 04.08.2016 15:29
 */

namespace app\controllers;

use app\models\Participant;
use Yii;
use app\models\Work;
use yii\helpers\FileHelper;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\web\Controller;
use Alchemy\Zippy\Zippy;
use yii\web\NotFoundHttpException;
use yii\web\Response;

class FileController extends Controller {

	private $archive;
	const ARCHIVE_NAME = 'works.zip';

	public function actionIndex() {
		$can_edit = \Yii::$app->user->can('editWork');

		if (!$can_edit) {
			throw new NotFoundHttpException( 'Страница не найдена' );
		}

		$works = Work::find()->count();

		return $this->render( 'index',
			[
				'worksCount' => $works,
			] );
	}

	private function createArchive() {
		$zippy = Zippy::load();

		$this->archive = $zippy->create( $this->getArchivePath(),
			array( 'dummy.txt' => Yii::getAlias( '@webroot/uploads/.gitkeep' ) ) );
	}

	private function loadArchive() {
		$zippy         = Zippy::load();
		$this->archive = $zippy->open( $this->getArchivePath() );
	}

	private function cleanArchive() {
		$this->loadArchive();
		$this->archive->removeMembers( array( 'dummy.txt' ) );
	}

	private function getPath() {
		return Yii::getAlias( '@webroot/uploads/works-sorted/' );
	}

	private function getArchivePath() {
		return Yii::getAlias( '@webroot/uploads/'.self::ARCHIVE_NAME );
	}

	/**
	 * @param int $offset
	 */
	public function actionAdd() {

		if ( ! Yii::$app->request->isAjax ) {
			return 'error';
		}

		$offset = (int) Yii::$app->request->post( 'offset' );

		$works = Work::find()->limit( 3 )->offset( $offset )->all();
		ini_set( 'max_execution_time', 0 );
		$this->loadArchive();


		foreach ( $works as $work ) {
			$nomination_name = $this->sanitize_file_name( $work->nominationName );

			$path      = $nomination_name . '/';
			$info_path = $path . 'info/';


			$info_file = Yii::getAlias( '@webroot/uploads/works-sorted/' ) . 'info.txt';
			$handle = fopen( $info_file, 'w' ) or die( 'Cannot open file:  ' . $info_file );

			$regions = Participant::getRegionsWithCode();

			$index = isset( $regions[ $work->participant->region ] ) ? $work->participant->region : '00';

			$region = $regions[ $index ];

			$file_url = false;

			if ( $work->file_name ) {
				$file_url = $work->fileUrl;
			}


			$work_url = Url::to( [ '/work/view', 'id' => $work->id ], true );

			$profileUrl = Url::to( [ '/participant/profile', 'id' => $work->participant->user_id ], true );

			$data = <<<INFO
Информация об участнике\r\n
========================\r\n
ID участника: {$work->participant->user_id}\r\n
ФИО: {$work->participant->name}\r\n
E-mail: {$work->user->email}\r\n
СМИ: {$work->participant->smi_name}\r\n
Сайт: {$work->participant->smi_url}\r\n
Тип сми: {$work->participant->smi_type_readable}\r\n
Регион: {$region}\r\n
URL участника на сайте конкурса: {$profileUrl}\r\n
URL логотипа издания: {$work->getlogoUrl()}\r\n
URL фото учаcтника: {$work->getPictureUrl()}\r\n
\r\n
Информация о работе\r\n
========================\r\n
Номинация: {$work->nominationName}\r\n
Описание работы: {$work->title}\r\n
\r\n
Оценить работу: {$work_url}\r\n
\r\n
URL файла работы: {$file_url}
INFO;


			fwrite( $handle, $data );
			fclose( $handle );

			$this->archive->addMembers( array(
				$info_path . $work->id . ' - информация.txt' => $info_file
			) );

			if ( $work->file_name && file_exists( $work->getFilePath() ) ) {
				$this->archive->addMembers( array(
					$path . $work->id . '.' . $work->file_type => $work->getFilePath()
				) );
			}
			if ( $work->picture && file_exists( $work->getPicturePath() ) ) {
				$this->archive->addMembers( array(
					$info_path . $work->id . ' - фото участника.' . pathinfo( $work->picture,
						PATHINFO_EXTENSION ) => $work->getPicturePath()
				) );
			}
			if ( $work->logo && file_exists( $work->getLogoPath() ) ) {
				$this->archive->addMembers( array(
					$info_path . $work->id . ' - логотип СМИ.' . pathinfo( $work->logo,
						PATHINFO_EXTENSION ) => $work->getLogoPath()
				) );

			}

			$offset ++;

		}

		Yii::$app->response->format = Response::FORMAT_JSON;

		return [ 'offset' => $offset ];

	}

	public function actionCopy() {

		if ( ! Yii::$app->request->isAjax ) {
			return 'error';
		}

		$offset = (int) Yii::$app->request->post( 'offset' );

		Yii::$app->response->format = Response::FORMAT_JSON;

		if ( $offset == - 1 ) {
			$this->zipFolder();
			return ['offset' => -1];
		} elseif ( $offset == 0 ) {
			$files_path = $this->getPath();
			FileHelper::removeDirectory( $files_path );
			FileHelper::createDirectory( $files_path );
			if (is_file($this->getArchivePath())) {
				unlink($this->getArchivePath());
			}
		}

		$works = Work::find()->limit( 3 )->offset( $offset )->all();
		ini_set( 'max_execution_time', 0 );


		foreach ( $works as $work ) {
			$nomination_name = $this->sanitize_file_name( $work->nominationName );

			$path      = $this->getPath() . $nomination_name . '/';
			$info_path = $path . 'info/';
			FileHelper::createDirectory( $info_path );


			$info_file = $info_path . $work->id . ' - информация.txt';
			$handle = fopen( $info_file, 'w' ) or die( 'Cannot open file:  ' . $info_file );

			$regions = Participant::getRegionsWithCode();

			$index = isset( $regions[ $work->participant->region ] ) ? $work->participant->region : '00';

			$region = $regions[ $index ];

			$file_url = false;

			if ( $work->file_name ) {
				$file_url = $work->fileUrl;
			}


			$work_url = Url::to( [ '/work/view', 'id' => $work->id ], true );

			$profileUrl = Url::to( [ '/participant/profile', 'id' => $work->participant->user_id ], true );

			$data = <<<INFO
Информация об участнике\r\n
========================\r\n
ID участника: {$work->participant->user_id}\r\n
ФИО: {$work->participant->name}\r\n
СМИ: {$work->participant->smi_name}\r\n
Сайт: {$work->participant->smi_url}\r\n
Тип сми: {$work->participant->smi_type_readable}\r\n
Регион: {$region}\r\n
URL участника на сайте конкурса: {$profileUrl}\r\n
URL логотипа издания: {$work->getlogoUrl()}\r\n
URL фото учаcтника: {$work->getPictureUrl()}\r\n
\r\n
Информация о работе\r\n
========================\r\n
Номинация: {$work->nominationName}\r\n
Описание работы: {$work->title}\r\n
\r\n
Оценить работу: {$work_url}\r\n
\r\n
URL файла работы: {$file_url}
INFO;


			fwrite( $handle, $data );
			fclose( $handle );

			if ( $work->file_name && file_exists( $work->getFilePath() ) ) {
				copy( $work->getFilePath(), $path . $work->id . '.' . $work->file_type );
			}
			if ( $work->picture && file_exists( $work->getPicturePath() ) ) {
				copy( $work->getPicturePath(), $info_path . $work->id . ' - фото участника.' . pathinfo( $work->picture,
						PATHINFO_EXTENSION ) );
			}
			if ( $work->logo && file_exists( $work->getLogoPath() ) ) {

				copy( $work->getLogoPath(), $info_path . $work->id . ' - логотип СМИ.' . pathinfo( $work->logo,
						PATHINFO_EXTENSION ) );
			}

			$offset ++;

		}


		return [ 'offset' => $offset ];

	}

	public function zipFolder() {
		$this->createArchive();
		$this->archive->addMembers( array(
			'.' => $this->getPath()
		) );

		$this->cleanArchive();
		FileHelper::removeDirectory( $this->getPath() );
	}

	function sanitize_file_name( $filename ) {
		$filename_raw  = $filename;
		$special_chars = array(
			"?",
			"[",
			"]",
			"/",
			"\\",
			"=",
			"<",
			">",
			":",
			";",
			",",
			"'",
			"\"",
			"&",
			"$",
			"#",
			"*",
			"(",
			")",
			"|",
			"~",
			"`",
			"!",
			"{",
			"}"
		);
		$filename      = str_replace( $special_chars, '', $filename );
		$filename      = preg_replace( '/[\s]+/', ' ', $filename );
		$filename      = preg_replace( '/[-]+/', '-', $filename );
		$filename      = trim( $filename, '.-_' );

		return $filename;
	}
}

controllers/WorkController.php
<?php

namespace app\controllers;

use app\models\WorkCategory;
use app\models\WorkForm;
use app\models\WorkMark;
use Yii;
use app\models\Work;
use app\models\search\Work as WorkSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\Response;
use yii\web\UploadedFile;
use yii\widgets\ActiveForm;

/**
 * WorkController implements the CRUD actions for Work model.
 */
class WorkController extends Controller {
    public function behaviors() {
        return [
            'verbs' => [
                'class'   => VerbFilter::className(),
                'actions' => [
                    'delete' => [ 'post' ],
                ],
            ],
        ];
    }

    public function actions() {
        return [
            'error'   => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Lists all Work models.
     *
     * @return mixed
     * @throws NotFoundHttpException
     */
    public function actionIndex() {

        if (\Yii::$app->user->isGuest) {
            throw new NotFoundHttpException( 'Страница не найдена' );
        }

        $can_edit = \Yii::$app->user->can('editWork');
        $can_rate = \Yii::$app->user->can('rateWork');

        $searchModel  = new WorkSearch();
        $dataProvider = $searchModel->search( Yii::$app->request->queryParams );

        $view = 'index';
        if (!$can_edit && !$can_rate) {
            $view = 'index_user';
        }
        return $this->render( $view, [
            'searchModel'  => $searchModel,
            'dataProvider' => $dataProvider,
            'can_edit' => $can_edit,
            'can_rate' => $can_rate
        ] );
    }

    /**
     * Displays a single Work model.
     *
     * @param integer $id
     *
     * @return mixed
     * @throws NotFoundHttpException
     */
    public function actionView( $id ) {
        $can_edit = \Yii::$app->user->can('editWork');
        $can_rate = \Yii::$app->user->can('rateWork');

        if (!$can_edit && !$can_rate) {
            throw new NotFoundHttpException( 'Страница не найдена' );
        }

        $model = $this->findModel( $id );

        if ($model && ($work_mark_data = \Yii::$app->request->post('WorkMark'))) {

            $user_id = null;
            if ($can_edit && \Yii::$app->request->post('user_id')) {
                $user_id = (int)\Yii::$app->request->post('user_id');
            } else if ($can_rate){
                $user_id = \Yii::$app->user->id;
            }

            if ($user_id) {
                WorkMark::deleteAll( [ 'user_id' => $user_id, 'work_id' => $model->id ] );
                foreach ( $work_mark_data as $mark_cat => $mark ) {
                    $mark_model                   = new WorkMark();
                    $mark_model->mark             = (int) $mark['mark'];
                    $mark_model->mark_category_id = (int) $mark_cat;
                    $mark_model->user_id          = $user_id;
                    $mark_model->work_id          = $model->id;
                    $mark_model->save();
                }
                \Yii::$app->session->setFlash('info', 'Работа №'.$model->id.' оценена!');
                return $this->redirect(['view', 'id'=>$model->id]);
            }
        }

        return $this->render( 'view', [
            'model' => $model,
            'can_rate' => $can_rate,
            'can_edit' => $can_edit
        ] );
    }

    /**
     * Creates a new Work model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     *
     * @return mixed
     * @throws NotFoundHttpException
     */
    public function actionAdd() {

	    if (time() > strtotime('01.09.2015 18:00')) {
		    return $this->render( 'end' );
	    }

        if ( ! Yii::$app->user->can( 'addWork' ) || Yii::$app->user->identity->activation_key ) {
            throw new NotFoundHttpException( 'Страница не найдена.' );
        }

//        if ( ( ! Yii::$app->user->can( 'editWork' ) && Yii::$app->user->identity->countWorks() ) ) {
//            return $this->redirect( [ 'user/profile' ] );
//        }

        $model = new Work( [ 'scenario' => 'add' ] );

        if ($errors = $this->performAjaxValidation($model)) {
            return $errors;
        }


        if ( $model->load( Yii::$app->request->post() ) && $model->save()) {

            if ( $model->sendEmail() ) {
                Yii::$app->session->setFlash( 'success', 'Работа добавлена!' );
            }
            return $this->redirect( [ 'user/profile' ] );
        } else {
            $model->scenario = 'form';
            return $this->render( 'create', [
                'model' => $model,
            ] );
        }
    }

    public function actionAdded() {
        return $this->render( 'added' );
    }

    /**
     * Generates hint for file input field depending on selected category
     *
     * @param $id
     *
     * @return string
     */
    public function actionGetFileInfo( $id = null ) {
        if (!\Yii::$app->request->isAjax) {
            return false;
        }
        if ( ! $id ) {
            $id = 1;
        }
        $cat = WorkCategory::findOne( $id );

        return $this->renderPartial( '_file-info', [
            'size'       => $cat->max_file_size,
            'exts'       => $cat->file_extensions,
            'additional' => $cat->file_text
        ] );

    }

    /**
     * Updates an existing Work model.
     * If update is successful, the browser will be redirected to the 'view' page.
     *
     * @param integer $id
     *
     * @return mixed
     * @throws NotFoundHttpException
     */
    public function actionUpdate( $id ) {


        $model           = $this->findModel( $id );
        $model->scenario = 'update';

        if (! Yii::$app->user->can('editWork',['user'=>$model->user_id]) || $model->getWorkMarks()->count()) {
            throw new NotFoundHttpException( 'Такой страницы не существует' );
        }

        if ($errors = $this->performAjaxValidation($model)) {
            return $errors;
        }

        if ( $model->load( Yii::$app->request->post() ) && $model->save() ) {
            return $this->redirect( [ 'update', 'id' => $model->id ] );
        } else {
            return $this->render( 'update', [
                'model' => $model,
            ] );
        }
    }

    /**
     * Deletes an existing Work model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     *
     * @param integer $id
     *
     * @return mixed
     * @throws NotFoundHttpException
     * @throws \Exception
     */
    public function actionDelete( $id ) {
        if (! Yii::$app->user->can('editWork')) {
            throw new NotFoundHttpException( 'Такой страницы не существует' );
        }

        $model = $this->findModel( $id );
        $model->deleteAllFiles();
        $model->delete();

        return $this->redirect( [ 'index' ] );
    }

    /**
     * Finds the Work model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     *
     * @param integer $id
     *
     * @return Work the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel( $id ) {
        if ( ( $model = Work::findOne( $id ) ) !== null ) {
            return $model;
        } else {
            throw new NotFoundHttpException( 'Страница не найдена.' );
        }
    }

    protected function performAjaxValidation($model)
    {
        if (Yii::$app->request->isAjax && $model->load(Yii::$app->request->post())) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ActiveForm::validate($model);
        }
    }
}

views/work/_file-info.php
<?php
/**
 * _file-extra.php
 * Created by h8every1 on 19.06.2015 18:10
 */
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $size integer */
/* @var $exts string */
/* @var $additional string */
?>Максимальный размер файла - <?= $size; ?>МБ, разрешенные типы файлов - <?= $exts; ?>
<?php if ($additional) { ?>
<div class="additional">
    <strong>Дополнительные ограничения к файлу:</strong><br>
    <?= nl2br($additional); ?>
</div>
<?php }

views/work/_form.php
<?php

use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Work */
/* @var $form yii\widgets\ActiveForm */

$participant = isset( $model->participant ) ? $model->participant : ( \Yii::$app->user->identity->participant ? \Yii::$app->user->identity->participant : false );
?>

<div class="work-form">
	<?php $form = ActiveForm::begin( [
		'options' => [
			'enctype' => 'multipart/form-data',
		]
	] );

	echo $form->errorSummary( $model );

	if ( Yii::$app->user->can( 'editWork' ) ) {
		echo $form->field( $model, 'user_id' )->dropDownList(
			ArrayHelper::map( \app\models\Participant::find()->asArray()->all(), 'user_id', 'name' )
		);
	} ?>

	<?= $form->field( $model, 'file' )->fileInput()->label( 'Загрузите файл' ) ?>
	<?php if ( ! $model->isNewRecord && $model->file_name && $model->file_type ) { ?>
		<div class="b-img-preview">
			<img src="<?= $model->fileUrl; ?>" alt="" width="300">
		</div>
	<?php } ?>

	<?= $form->field( $model, 'nomination' )->dropDownList(
		$model->nominations
	); ?>
	<?= $form->field( $model, 'title', [ 'enableAjaxValidation' => true ] )->textarea( [ 'rows' => 4 ] ) ?>

	<div class="row">
		<?php if ( $participant ) { ?>
			<div class="col-sm-6">
				<?= $form->field( $model, 'picture_file' )->fileInput() ?>
				<?php if ( $model->picture ) { ?>
					<div class="b-img-preview">
						<img src="<?= $model->pictureUrl; ?>" alt="" width="300">
					</div>
				<?php } ?>
			</div>
		<?php } ?>
		<div class="col-sm-6">
			<?= $form->field( $model, 'logo_file' )->fileInput() ?>
			<?php if ( $model->logo ) { ?>
				<div class="b-img-preview">
					<img src="<?= $model->logoUrl; ?>" alt="" width="300">
				</div>
			<?php } ?>
		</div>
	</div>

	<div class="form-group">
		<?= Html::submitButton( $model->isNewRecord ? 'Добавить работу' : 'Изменить работу',
			[ 'class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary' ] ) ?>
	</div>

	<?php ActiveForm::end(); ?>

</div>

views/work/_preview-1.php
<?php
/**
 * _preview-1.php
 * Created by h8every1 on 29.06.2015 19:57
 */
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Work */

?>
<iframe class="b-work--document" src="http://docs.google.com/viewer?url=<?= Html::encode( $model->fileUrl ) ?>&embedded=true" width="100%"
        height="600"></iframe>

views/work/_preview-2.php
<?php
/**
 * _preview-1.php
 * Created by h8every1 on 29.06.2015 19:57
 */
//use yii\helpers\FileHelper;
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Work */

?>
<div class="b-player b-player__audio">
    <audio src="<?= Html::encode( $model->fileUrl ) ?>" controls preload="auto">

    </audio>
</div>

views/work/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\search\Work */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="work-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'konkurs_id') ?>

    <?= $form->field($model, 'participant_id') ?>

    <?= $form->field($model, 'category_id') ?>

    <?= $form->field($model, 'file_name') ?>

    <?php // echo $form->field($model, 'file_type') ?>

    <?php // echo $form->field($model, 'title') ?>

    <?php // echo $form->field($model, 'date') ?>

    <?php // echo $form->field($model, 'smi_category') ?>

    <?php // echo $form->field($model, 'picture') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/work/added.php
<?php
/**
 * added.php
 * Created by h8every1 on 19.06.2015 18:23
 */

use yii\helpers\Html;

/* @var $this yii\web\View */

$this->title = 'Работа добавлена';
$this->params['breadcrumbs'][] = ['label' => 'Конкурсные работы', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="work-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>Ваша работа была успешно добавлена! Желаем удачи!</p>

</div>

views/work/create.php
<?php

use app\assets\ImageValidationAsset;
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Work */
ImageValidationAsset::register( $this );

$this->title = 'Добавление работы';
?>
<div class="container">
    <div class="work-create">

        <h1><?= Html::encode( $this->title ) ?></h1>

        <?= $this->render( '_form', [
            'model' => $model,
        ] ) ?>

    </div>
</div>

views/work/index.php
<?php

use app\models\Participant;
use yii\helpers\Html;
use kartik\grid\GridView;
use kartik\export\ExportMenu;
use yii\helpers\Url;
use app\widgets\Alert;

/* @var $this yii\web\View */
/* @var $searchModel app\models\search\Work */
/* @var $dataProvider yii\data\ActiveDataProvider */
/* @var $can_edit bool */
/* @var $can_rate bool */

$this->title                   = 'Конкурсные работы';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="work-index">

    <h1><?= Html::encode( $this->title ) ?></h1>
    <?= Alert::widget( [ 'closeButton' => false ] ) ?>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>
    <?php
    if ( $can_edit ) {

        $columns_template = [
            'picture'          => [
                'attribute' => 'picture',
                'value'     => function ( $model ) {
                    /* @var $model \app\models\search\Work */
                    return $model->pictureUrl . ':url';
                },
                'format'    => 'raw',
            ],
        ];

        $excelGridColumns = [
            'id',
            [
                'attribute' => 'participant.region',
                'filter'    => Participant::getRegionsWithCode(),
                'value'     => function ( $model ) {
                    $regions = Participant::getRegionsWithCode();

                    $index = isset( $regions[ $model->participant->region ] ) ? $model->participant->region : '00';

                    return $regions[ $index ];
                },

            ],
            'participant.name:raw',
            [
                'attribute' => 'participant.smi_type',
                'filter'    => Participant::getSmiTypes(),
                'value'     => function ( $model ) {
                    return $model->participant->smi_type_readable;
                },
            ],
            'participant.smi_name:raw',
            $columns_template['picture'],
            [
                'attribute' => 'logo',
                'value'     => function ( $model ) {
                    /* @var $model \app\models\search\Work */
                    return $model->logoUrl . ':url';
                },
                'format'    => 'raw',
            ],
            [
                'attribute' => 'nomination',
                'value'     => 'nominationName'
            ],
            'title:nl2br',
            [
                'label'  => 'Ссылка на файл работы',
                'value'  => function ( $model ) {
                    /* @var $model \app\models\search\Work */
                    $result = false;

                    if ( $model->file_name ) {
                        $result = $model->fileUrl . ':url';
                    }


                    return $result;
                },
                'format' => 'raw'
            ],
            [
                'label'  => 'Оценить работу',
                'value'  =>
                    function ( $model ) {
                        /* @var $model \app\models\search\Work */
                        return Url::to( [ 'work/view', 'id' => $model->id ], true ) . ':url';
                    },
                'format' => 'raw'
            ],
            [
                'attribute' => 'marksSum',
                'label'     => 'Оценка',
            ]
        ];

        // Renders a export dropdown menu
        echo ExportMenu::widget( [
            'dataProvider'     => $dataProvider,
            'columns'          => $excelGridColumns,
            'dropdownOptions'  => [
                'label' => 'Экспорт списка работ',
                'class' => 'btn btn-primary'
            ],
            'filename'         => 'Список_работ',
            'onRenderDataCell' => function (
                PHPExcel_Cell $cell,
                $value,
                $model,
                $key,
                $index,
                \kartik\export\ExportMenu $export
            ) {
                $value = $cell->getValue();
                if ( strpos( $value, ':url' ) !== false ) {
                    $value = str_replace( ':url', '', $value );
                    $cell->getHyperlink()->setUrl( $value );
                    $cell->setValue( $value );
                }

            }
        ] );
    }
    // end EXPORT


    $columns = [ ];

    $columns[] = 'id';

    if ( $can_edit ) {
        $columns[] = [
            'attribute' => 'participant.name',
            'value'     => function ( $model ) {
                /* @var $model \app\models\Work */
                return Html::a( $model->participant->name . ' (' . $model->participant->smi_name . ')',
                    \yii\helpers\Url::to( [ 'participant/profile', 'id' => $model->user_id ] ) ).
                    '<br>'.Html::a( $model->user->email, 'mailto:'.$model->user->email );
            },
//                'filter'=>'participant.name',
            'format'    => 'html'
        ];
        $columns[] = [
            'attribute'     => 'picture',
            'value'         => function ( $model ) {
                /* @var $model \app\models\search\Work */
                return $model->participant->type === Participant::TYPE_JOURNALIST ? '<a href="' . $model->pictureUrl . '" target="_blank">' . Html::img( $model->pictureThumbUrl ) . '</a>' : ' - ';
            },
            'format'        => 'html',
            'enableSorting' => false,
            'filter'        => false
        ];
        $columns[] = [
            'attribute'     => 'logo',
            'value'         => function ( $model ) {
                /* @var $model \app\models\search\Work */
                return '<a href="' . $model->logoUrl . '" target="_blank">' . Html::img( $model->logoThumbUrl ) . '</a>';
            },
            'format'        => 'html',
            'enableSorting' => false,
            'filter'        => false
        ];
    }

    $columns[] = [
        'attribute' => 'title',
        'value'     => function ( $model ) {
            return
                Html::img( $model->fileThumbUrl ).'<br>'.
                \yii\helpers\StringHelper::truncateWords($model->title,'10','...',true) . ' ' . Html::a( '<span class="glyphicon glyphicon-eye-open"></span> Просмотр',
                [ 'view', 'id' => $model->id ], [ 'class' => 'btn btn-xs btn-success' ] );
        },
        'format'    => 'html'

    ];

    $columns[] = [
        'attribute' => 'participant.smi_type',
        'filter'    => Participant::getSmiTypes(),
        'value'     => function ( $model ) {
            return $model->participant->smi_type_readable;
        },
    ];


    $columns[] = [
        'attribute' => 'nomination',
        'filter'    => $searchModel::allNominations(),
        'value'     => function ( $model ) {
            return $model->nominationName;
        }
    ];

    if ( $can_edit ) {
        $columns[] = [
            'attribute' => 'has_marks',
            'label'     => 'Оценено?',
            'filter'    => [ 'Нет', 'Да' ],
            'value'     => function ( $model ) {
                return $model->marked;
            },
            'format'    => 'boolean'
        ];
    }

    if ( $can_edit ) {
        $columns[] = [
            'attribute' => 'marksSum',
            'label'     => 'Оценка',
        ];
        $columns[] = [
            'class' => yii\grid\ActionColumn::className(),
        ];
    }

    if ( $can_edit ) {
        echo Html::a('Скачать архив работ',['file/index'],['class'=>'btn btn-danger']);
    }
    ?>
    <?= GridView::widget( [
        'dataProvider' => $dataProvider,
        'filterModel'  => $searchModel,
        'columns'      => $columns,
    ] ); ?>

</div>